<div class="abovefooterdiv">
  <div class ="innerfooterdiv">
      <div class="abovefooterheadingdiv">
      <h2 class="abovefooterdivh2"> STAY CONNECTED </h2>
      </div>
      <div class="inputdiv">
      <input type ="text" placeholder="ENTER YOUR EMAIL" class="inputemailstyle"/>
      </div>
      <div class="abovefooterbuttondiv">
        <button class="button1">WOMEN</button>
        <button class="button2">MEN</button>
   </div>
  </div>
   
</div>


      
