<div class="buttonimgstyle">
<i class="fas fa-search searchiconstyle" ></i></div>

  <script type="text/javascript">
		require(['jquery'], function($) {	

      $(".buttonimgstyle").hover(function(){
        $(".buttonimgstyle").addClass("jquerystylebutton");
        $(".fas.fa-search").addClass("jqueryiconsearch");
        $(".block.block-search").addClass("jquerysearch");
        $(".search").addClass("searchdiv");
       });
        });
    </script>
     
    