<div class="coprightdiv">
    <div class="innercopyrightdiv">
    <div class="coprightdiv1">
    <img src="<?php echo $this->getViewFileUrl('img/global.png'); ?>" class="dollorglob" />
    </div>
    <div class="coprightdiv2">
        <a class="copyrightlink privacylink">PRIVACY POLICY</a>
        <a class="copyrightlink termsandcondition">TERMS AND CONDITIONS</a>
        <a class="copyrightlink sitemap">SITE MAP</a>
    </div>
    <div class="coprightdiv3">
        <p class="paragraphdiv">© RUDSAK 2016.ALL RIGHTS RESERVED</p>
    </div>
</div>
</div>

