<div class="linkfooter">
<div class="linkinnerfooter">
<div class="linkfooterdiv1">
 <h2 class="linkfooterh1">CUSTOMER SERVICE</h2>
 <a  href="#" class="linkfooterp1">FAQ</a>
 <a  href="#" class="linkfooterp1">ORDER STATUS</a>
 <a  href="#" class="linkfooterp1">SHIPPING INFORMATION</a>
 <a  href="#" class="linkfooterp1">RETURN & EXCHANGES</a>
 <a  href="#" class="linkfooterp1">SIZE CHART</a>
 <a  href="#" class="linkfooterp1">CONTACT US</a>
</div>
<div class="linkfooterdiv2">
<h2 class="linkfooterh2">RUDSAK</h2>
 <a  href="#" class="linkfooterp1">ABOUT US</a>
 <a  href="#" class="linkfooterp1">STORE LOCATOR</a>
 <a href="#" class="linkfooterp1">GIFT CARDS</a>
 <a  href="#" class="linkfooterp1">CAREER</a>
 <a  href="#" class="linkfooterp1">WHOLESALE</a>
 <a  href="#" class="linkfooterp1">PRESS INQUIRIES</a>
 <a  href="#" class="linkfooterp1">CORPORATE GIFTING</a>
</div>
<div class="linkfooterdiv3">
<h2 class="linkfooterh3">CONNECT WITH US</h2>
<a  href="#" class="linkfooterdiv3a1"><i class="fab fa-facebook-f"></i></a>
<a  href="#" class="linkfooterdiv3a1"><i class="fab fa-tumblr"></i></a>
<a   href="#" class="linkfooterdiv3a1"><i class="fab fa-pinterest-p"></i></a>
<a  href="#"  class="linkfooterdiv3a1"><i class="fab fa-instagram"></i></a>
<a  href="#" class="linkfooterdiv3a1"><i class="fab fa-youtube"></i></a>
</div>
</div>
</div>